// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDDOcl_fHN52DUzxp5-X_eSkbwk-iYu3M',
    appId: '1:724253407928:ios:2eee5f5f60f60c633ad24d',
    messagingSenderId: '724253407928',
    projectId: 'ecotrack-82e79',
    storageBucket: 'ecotrack-82e79.firebasestorage.app',
    iosBundleId: 'com.example.ecotrack',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDDOcl_fHN52DUzxp5-X_eSkbwk-iYu3M',
    appId: '1:724253407928:ios:2eee5f5f60f60c633ad24d',
    messagingSenderId: '724253407928',
    projectId: 'ecotrack-82e79',
    storageBucket: 'ecotrack-82e79.firebasestorage.app',
    iosBundleId: 'com.example.ecotrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR9VtxRuc3MvqqcV1DUEFIM86I5lbRkhY',
    appId: '1:724253407928:web:000670871b3068933ad24d',
    messagingSenderId: '724253407928',
    projectId: 'ecotrack-82e79',
    authDomain: 'ecotrack-82e79.firebaseapp.com',
    storageBucket: 'ecotrack-82e79.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR9VtxRuc3MvqqcV1DUEFIM86I5lbRkhY',
    appId: '1:724253407928:web:000670871b3068933ad24d',
    messagingSenderId: '724253407928',
    projectId: 'ecotrack-82e79',
    authDomain: 'ecotrack-82e79.firebaseapp.com',
    storageBucket: 'ecotrack-82e79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz-Jn4BEDGXcUhH9NVOnSXM6yhxDAp_QQ',
    appId: '1:724253407928:android:3dfa9d24cdbdc8db3ad24d',
    messagingSenderId: '724253407928',
    projectId: 'ecotrack-82e79',
    storageBucket: 'ecotrack-82e79.firebasestorage.app',
  );
}
